script:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    git config user.name 'Travis CI';
    git config user.email 'i@zhuweiyou.com';
    git push https://${GITEE_TOKEN}@gitee.com/npm/weixin-game-helper.git master -f;
    fi

branches:
  only:
    - master
